# Generated by Django 5.1.4 on 2024-12-14 09:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=25)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('profimg', models.ImageField(blank=True, null=True, upload_to='User_Profile_Images/')),
            ],
        ),
        migrations.CreateModel(
            name='FriendList',
            fields=[
                ('S_no', models.AutoField(primary_key=True, serialize=False)),
                ('frnd_img', models.ImageField(blank=True, null=True, upload_to='Friends_Images/')),
                ('frnd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to='myblog.datas')),
                ('me', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='myblog.datas')),
            ],
        ),
        migrations.CreateModel(
            name='PostDatas',
            fields=[
                ('idpost', models.AutoField(primary_key=True, serialize=False)),
                ('namepost', models.CharField(max_length=200, unique=True)),
                ('datepost', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagepost', models.ImageField(blank=True, null=True, upload_to='Post_Images/')),
                ('contpost', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myblog.datas')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myblog.postdatas')),
            ],
        ),
    ]
