# Generated by Django 5.1.4 on 2024-12-15 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendlist',
            name='frnd_email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='friendlist',
            name='my_email',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
