# Generated by Django 5.1.4 on 2024-12-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_changepassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChangePassword',
        ),
    ]
